// Indicator knowledge base — what each metric means, Buffett lens, Dalio lens
// ─── Indicator knowledge base ─────────────────────────────────────────────────
export const INDICATORS = {
  // INFLATION
  cpi: {
    name: 'Consumer Price Index (CPI)',
    series: 'CPIAUCSL · BLS · Monthly',
    category: 'Inflation',
    what: 'Measures the average change in prices paid by urban consumers for a basket of goods and services — food, housing, transport, healthcare, clothing.',
    why: 'The Fed\'s primary inflation target is 2% annual CPI growth. When CPI runs above 2%, the Fed raises rates to cool spending. When it falls below, the Fed cuts rates to stimulate.',
    buffett: 'Buffett avoids companies without pricing power — they get squeezed when input costs (PPI) rise faster than they can raise prices. Companies with pricing power expand margins in inflationary environments.',
    dalio: 'Dalio\'s regime framework uses inflation as one of two axes. Rising inflation shifts the favorable asset mix toward real assets (energy, gold, commodities, TIPS) and away from long-duration bonds and growth stocks.',
    read: (v, d) => v > 3 ? `Above 3% — Fed likely to stay restrictive` : v > 2 ? `Moderately above Fed\'s 2% target` : `Near or below Fed target — easing more likely`,
    thresholds: [{ val: 2, label: 'Fed target', color: '#1D9E75' }, { val: 4, label: 'Problem zone', color: '#E24B4A' }],
  },
  ppi: {
    name: 'Producer Price Index (PPI)',
    series: 'PPIACO · BLS · Monthly',
    category: 'Inflation',
    what: 'Measures price changes from the seller\'s perspective — what producers receive for their output. Tracks commodities, manufacturing, and services before they reach consumers.',
    why: 'PPI leads CPI by 2–3 months. When producer costs rise, companies eventually pass them to consumers. A widening gap between PPI and CPI means margin pressure for companies.',
    buffett: 'When PPI rises faster than a company can raise prices, margins compress. Buffett\'s moat assessment partly tests this: can the business pass on cost increases without losing customers?',
    dalio: 'PPI is an early signal of inflationary regime shifts — particularly useful for detecting commodity-driven inflation before it shows up in CPI.',
    read: (v) => v > 4 ? `Elevated — watch for CPI to follow higher` : v > 2 ? `Moderate — some pass-through pressure` : `Contained — cost environment manageable`,
    thresholds: [{ val: 2, label: 'Benign', color: '#1D9E75' }, { val: 4, label: 'Elevated', color: '#E24B4A' }],
  },
  breakeven_5y: {
    name: '5-Year Breakeven Inflation Rate',
    series: 'T5YIE · FRED · Daily',
    category: 'Inflation',
    what: 'The market\'s best guess at average inflation over the next 5 years. Calculated as the difference between the 5-year nominal Treasury yield and the 5-year TIPS (inflation-protected) yield.',
    why: 'Unlike CPI (backward-looking), breakevens are forward-looking — they show what bond markets expect. When breakevens rise sharply, it signals the market is losing confidence in the Fed\'s ability to contain inflation.',
    buffett: 'Buffett watches long-term inflation expectations because they affect how he discounts future cash flows. High expected inflation means future dollars are worth less, compressing valuations.',
    dalio: 'Breakevens are central to Dalio\'s All Weather framework. When they rise above 2.5%, TIPS and commodities become attractive relative to nominal bonds.',
    read: (v) => v > 2.8 ? `Above 2.8% — market doubts Fed can reach 2% target` : v > 2.2 ? `Slightly elevated — inflation expectations anchored but high` : `Well-anchored — market confident in Fed`,
  },
  // INTEREST RATES & YIELD CURVE
  fed_funds: {
    name: 'Federal Funds Rate',
    series: 'FEDFUNDS · Fed · Monthly',
    category: 'Interest Rates',
    what: 'The interest rate at which banks lend to each other overnight. The Fed\'s primary tool for controlling inflation and stimulating growth. Every other interest rate — mortgages, car loans, credit cards, corporate bonds — is priced off this rate.',
    why: 'Higher rates slow the economy by making borrowing expensive. Lower rates stimulate it by making borrowing cheap. The rate level determines whether companies refinance debt at a profit or a loss, and how much consumers can afford to spend.',
    buffett: 'Buffett famously calls interest rates "gravity" for asset prices. Low rates make future earnings more valuable (higher multiples). High rates compress multiples and punish companies with floating-rate debt.',
    dalio: 'The Fed\'s rate cycle is a key driver of Dalio\'s short-term debt cycle. Rate hikes slow credit growth; rate cuts stimulate it. Where we are in this cycle determines regime.',
    read: (v) => v > 4.5 ? `Restrictive — actively slowing economy to fight inflation` : v > 3 ? `Above neutral — moderately restrictive` : v > 1.5 ? `Near neutral — balanced` : `Stimulative — economy needs support`,
  },
  spread_2s10s: {
    name: 'Yield Curve Spread (2s10s)',
    series: 'T10Y2Y · FRED · Daily',
    category: 'Interest Rates',
    what: 'The difference between the 10-year Treasury yield and the 2-year Treasury yield. Normally positive (upward sloping curve) because locking money up longer should pay more. When it turns negative (inverted), it\'s a historically reliable recession signal.',
    why: 'The 2-year yield reflects Fed rate expectations. The 10-year reflects long-term growth and inflation expectations. When the 2-year exceeds the 10-year, the market is saying: the economy will slow enough that the Fed will have to cut rates — and that usually means recession.',
    buffett: 'Buffett doesn\'t time the market using yield curve signals, but an inverted curve affects his cash allocation decisions and acquisition pricing.',
    dalio: 'The yield curve shape is central to Dalio\'s debt cycle framework. Sustained inversion has preceded every recession since 1955 with a 12-18 month lag.',
    read: (v) => v < 0 ? `⚠ Inverted — recession signal. Has predicted 7 of 8 recessions` : v < 0.5 ? `Slightly positive — near neutral, watch closely` : `Normal — economy expects continued growth`,
    thresholds: [{ val: 0, label: 'Inversion threshold', color: '#E24B4A' }],
  },
  yield_10y: {
    name: '10-Year Treasury Yield',
    series: 'DGS10 · Fed · Daily',
    category: 'Interest Rates',
    what: 'The annual return on a 10-year US government bond. The most important benchmark interest rate in the world — used to price mortgages, corporate bonds, and to discount the value of all future cash flows.',
    why: 'Rising 10-year yields compress stock valuations (especially long-duration growth stocks) because future earnings become less valuable when discounted at a higher rate. They also tighten financial conditions for companies refinancing debt.',
    buffett: 'The 10-year yield is literally the denominator in Buffett\'s discounted cash flow models. He has said he would be very bullish on stocks if the 10-year were at 2%, and far less so at 5%.',
    dalio: 'The real yield (10yr minus inflation) matters most. Negative real yields push investors into real assets (gold, commodities). Positive and rising real yields attract capital to bonds from equities.',
    read: (v) => v > 5 ? `Elevated — significant pressure on growth valuations` : v > 4 ? `High — restrictive for rate-sensitive sectors` : v > 3 ? `Moderate — manageable for most companies` : `Low — accommodative for equities`,
  },
  // GROWTH & ACTIVITY
  pmi_mfg: {
    name: 'ISM Manufacturing PMI',
    series: 'NAPM · ISM/FRED · Monthly',
    category: 'Growth',
    what: 'A survey of purchasing managers at over 400 manufacturing companies. They report on new orders, production, employment, supplier delivery times, and inventories. The result is a diffusion index where 50 = neutral, above 50 = expanding, below 50 = contracting.',
    why: 'PMI is one of the most reliable leading indicators — it turns before the economy does. New orders sub-index is particularly important: today\'s orders become tomorrow\'s production and employment. Three consecutive months below 50 historically signals recession risk.',
    buffett: 'Buffett tracks PMI for his industrial holdings (CAT, DE, GE). A PMI above 52 for 3+ months is typically when he sees earnings beats from these companies.',
    dalio: 'PMI is Dalio\'s primary real-time gauge of the growth dimension of his regime framework. Below 50 shifts the regime toward slowdown; above 52 suggests expansion.',
    read: (v) => v > 55 ? `Strong expansion — broad-based manufacturing growth` : v > 52 ? `Solid expansion — good for industrials and materials` : v > 50 ? `Mild expansion — just above neutral` : v > 47 ? `Mild contraction — watch for deterioration` : `Contraction — manufacturing in recession territory`,
    thresholds: [{ val: 50, label: 'Expansion/contraction', color: '#BA7517' }, { val: 55, label: 'Strong expansion', color: '#1D9E75' }],
  },
  unemployment: {
    name: 'Unemployment Rate',
    series: 'UNRATE · BLS · Monthly',
    category: 'Growth',
    what: 'The percentage of the labor force that is actively looking for work but cannot find it. Does NOT include people who have stopped looking. The Fed\'s mandate is "maximum employment" — generally interpreted as unemployment around 4%.',
    why: 'Low unemployment means workers have bargaining power, wages rise, spending increases, and inflation tends to go up. High unemployment means the opposite. The "natural rate" is roughly 4–4.5% — the lowest sustainable level without triggering inflation.',
    buffett: 'Buffett watches unemployment to gauge consumer spending power. His consumer businesses (KO, AXP, MCD) do better when unemployment is low and consumers feel secure.',
    dalio: 'Unemployment is a lagging indicator — it rises after the economy has already weakened. Dalio focuses more on leading indicators like PMI and credit spreads than on unemployment.',
    read: (v) => v < 4 ? `Very low — tight labor market, wage pressure, supports consumer` : v < 4.5 ? `Near natural rate — balanced labor market` : v < 6 ? `Rising — labor market loosening, Fed may ease` : `High — significant economic weakness`,
  },
  jobless_claims: {
    name: 'Initial Jobless Claims',
    series: 'ICSA · DOL · Weekly',
    category: 'Growth',
    what: 'The number of people filing for unemployment benefits for the first time each week. Unlike the monthly unemployment rate, this is published every Thursday — making it the most timely labor market signal available.',
    why: 'A sudden spike in claims (say, from 220k to 280k+) is one of the earliest warning signs of economic deterioration. Sustained claims above 300k historically correlate with rising unemployment and recession.',
    buffett: 'Weekly claims are a real-time check on the economy. Buffett\'s insurance businesses (GEICO, BHRG) are directly affected — rising unemployment means more claims and premium pressure.',
    dalio: 'Dalio\'s team watches weekly claims as a high-frequency leading indicator, alongside credit spreads and PMI, to detect regime transitions early.',
    read: (v) => v > 350000 ? `⚠ Elevated — significant layoff activity` : v > 260000 ? `Rising — labor market weakening` : v > 220000 ? `Normal range — stable labor market` : `Low — very tight labor market`,
  },
  // CREDIT & STRESS
  hy_spread: {
    name: 'High Yield Credit Spread',
    series: 'BAMLH0A0HYM2 · ICE BofA · Daily',
    category: 'Credit & Stress',
    what: 'The extra yield investors demand to hold junk bonds (sub-investment grade) instead of risk-free Treasuries. When companies are healthy and investors are confident, this spread is tight (low). When stress rises, the spread widens as investors demand more compensation for default risk.',
    why: 'Credit markets are smarter than equity markets — they price in stress before stocks do. A widening spread of 100+ basis points over 4 weeks has historically preceded equity drawdowns of 10%+ with 3–6 months lead time.',
    buffett: 'Buffett watches credit spreads as a signal of systemic risk. When HY spreads blow out (2008, 2020), he gets ready to deploy capital — the panic creates the opportunities he waits for.',
    dalio: 'HY spreads are central to Dalio\'s stress assessment. Wide spreads signal that the credit machine is seizing up — the mechanism that drives both the short-term and long-term debt cycles.',
    read: (v) => v > 7 ? `⚠ Very wide — severe financial stress, recession likely` : v > 5 ? `Wide — elevated stress, risk-off environment` : v > 3.5 ? `Normal — healthy credit markets` : `Tight — investors complacent, risk-on`,
    thresholds: [{ val: 3.5, label: 'Healthy', color: '#1D9E75' }, { val: 5.5, label: 'Stress', color: '#E24B4A' }],
  },
  fin_stress: {
    name: 'Financial Stress Index',
    series: 'STLFSI2 · St. Louis Fed · Weekly',
    category: 'Credit & Stress',
    what: 'A composite index that combines 18 weekly data series including interest rate spreads, yield differences, and other indicators of financial market stress. Zero represents normal conditions; positive values indicate above-average stress.',
    why: 'Financial conditions determine whether credit flows freely or tightens. When the index spikes above 1, it typically means banks are tightening lending standards, which chokes off business investment and consumer spending.',
    buffett: 'Buffett\'s Berkshire acts as a "financial first responder" when stress is extreme — deploying capital into preferred shares and crisis loans. The stress index tells him when that moment is approaching.',
    dalio: 'This is one of Dalio\'s core regime transition signals. A sustained reading above 1 typically coincides with the shift from inflationary growth to stagflation or deflationary slowdown.',
    read: (v) => v > 2 ? `⚠ Extreme stress — financial conditions severely tightening` : v > 1 ? `Elevated stress — conditions tightening` : v > 0 ? `Mild stress — some tightening` : `Normal to loose — financial conditions accommodative`,
  },
  // CONSUMER
  consumer_sent: {
    name: 'Michigan Consumer Sentiment',
    series: 'UMCSENT · U. Michigan · Monthly',
    category: 'Consumer',
    what: 'A monthly survey of ~500 US households asking about their financial situation, expectations for the economy, and buying intentions. Long-run average is around 87. Current reading of 57 is historically weak.',
    why: 'Consumer sentiment leads consumer spending by about 3 months. When confidence falls, people cut back on big purchases (cars, appliances, vacations). Since consumer spending is 70% of US GDP, a sustained sentiment decline is a serious warning.',
    buffett: 'Buffett\'s consumer-facing businesses (KO, MCD, AXP) are directly tied to sentiment. He watches this alongside retail sales and credit card data to gauge consumer health.',
    dalio: 'Consumer sentiment is a useful confirmation signal for Dalio\'s regime framework — not a primary driver, but it validates whether growth signals from PMI and LEI are showing up in actual behavior.',
    read: (v) => v > 85 ? `Strong — consumers confident, spending likely robust` : v > 70 ? `Decent — some caution but manageable` : v > 60 ? `Weak — consumers nervous, spending may soften` : `Very weak — significant consumer pullback likely`,
  },
  savings_rate: {
    name: 'Personal Savings Rate',
    series: 'PSAVERT · BEA · Monthly',
    category: 'Consumer',
    what: 'The percentage of disposable personal income that Americans save rather than spend. Pre-pandemic average was around 7–8%. Pandemic peak was 33%. Current rate below 5% means Americans are spending most of their income.',
    why: 'A very low savings rate can be a warning sign — it means consumers have little buffer if income drops. But it also means current spending is strong. Rising savings (consumers pulling back) typically precedes economic slowdowns.',
    buffett: 'A low savings rate benefits Buffett\'s consumer businesses short-term but raises durability questions. He prefers businesses that thrive even when consumers become more cautious.',
    dalio: 'Savings rate feeds into Dalio\'s view of debt cycle sustainability. Very low savings + high debt = vulnerable consumer balance sheet, which amplifies any economic downturn.',
    read: (v) => v > 8 ? `Healthy cushion — consumers have buffer` : v > 5 ? `Modest — reasonable but limited buffer` : v > 3 ? `Low — consumers spending most income, limited buffer` : `Very low — consumer financial vulnerability elevated`,
  },
  // SENTIMENT
  fear_greed_score: {
    name: 'CNN Fear & Greed Index',
    series: 'CNN · 7 sub-indicators · Daily',
    category: 'Sentiment',
    what: 'A composite of 7 market-based indicators: S&P 500 momentum vs 125-day moving average, 52-week highs vs lows, McClellan breadth index, put/call ratio, VIX level, junk bond demand, and safe haven demand. Score 0 = extreme fear, 100 = extreme greed.',
    why: 'Buffett\'s most famous quote applies directly: "Be fearful when others are greedy, and greedy when others are fearful." Extreme fear readings (below 20) have historically been strong medium-term buying signals. Extreme greed (above 80) often precedes corrections.',
    buffett: 'This index operationalizes Buffett\'s core philosophy. He has deployed his largest investments (2008 crisis, March 2020) when fear was at extremes — not because he was timing the market, but because business quality became available at distressed prices.',
    dalio: 'Dalio uses sentiment as a contrarian overlay — not a primary regime signal. When sentiment is extreme, positioning is likely crowded and reversals become more probable.',
    read: (v) => v < 20 ? `Extreme fear — historically strong contrarian buy signal` : v < 40 ? `Fear — market pessimistic, often good for long-term investors` : v < 60 ? `Neutral — balanced sentiment` : v < 80 ? `Greed — optimism elevated, be selective` : `Extreme greed — crowded positioning, caution warranted`,
    thresholds: [{ val: 25, label: 'Buy signal zone', color: '#1D9E75' }, { val: 75, label: 'Caution zone', color: '#E24B4A' }],
  },
  vix: {
    name: 'VIX — Volatility Index',
    series: '^VIX · CBOE · Daily',
    category: 'Sentiment',
    what: 'Measures the market\'s expectation of 30-day volatility implied by S&P 500 options. Often called the "fear gauge." A VIX of 20 means the market expects the S&P 500 to move about 20% annualized, or roughly 1.15% per day.',
    why: 'VIX spikes during market crises and falls during calm periods. Below 15 = complacency. Above 30 = fear. Above 40 = crisis-level panic. Importantly, VIX is mean-reverting — extreme readings tend to revert, making them timing signals.',
    buffett: 'When VIX spikes above 40, Buffett\'s deals flow in. His investments in Goldman Sachs (2008) and Bank of America (2011) both happened at moments of extreme VIX. He sells put options in low-VIX environments — collecting premium when others are too calm.',
    dalio: 'VIX is a key component of Dalio\'s financial stress assessment. A sustained VIX above 25 signals that risk parity strategies (which assume stable volatility) need to de-lever.',
    read: (v) => v > 40 ? `Crisis — panic-level fear, contrarian opportunity zone` : v > 30 ? `High fear — significant uncertainty, defensive positioning` : v > 20 ? `Elevated — markets cautious` : v > 15 ? `Normal — typical market conditions` : `Complacent — low volatility, risk may be underpriced`,
  },
}